apiVersion: v1
kind: Namespace
  name: ndc-cass-instance
spec: {}
--
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
  namespace: ndc-cass-instance
spec:
  clusterName: cluster1
  serverType: cassandra
  serverVersion: 3.11.11
  managementApiAuth:
    insecure: {}
  size: 2
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: ocs-external-storagecluster-ceph-rbd
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  racks:
    - name: rack1
      nodeAffinityLabels:
                cass-zone: zone1
    - name: rack2
      nodeAffinityLabels:
                cass-zone: zone2
  config:
    cassandra-yaml:
      authenticator: org.apache.cassandra.auth.PasswordAuthenticator
      authorizer: org.apache.cassandra.auth.CassandraAuthorizer
      role_manager: org.apache.cassandra.auth.CassandraRoleManager
    jvm-options:
      initial_heap_size: 800M
      max_heap_size: 800M
      additional-jvm-opts:
        - "-Dcassandra.system_distributed_replication_dc_names=dc1"
        - "-Dcassandra.system_distributed_replication_per_dc=2"
  podTemplateSpec:
    spec:
      initContainers:
        - name: server-config-init
          securityContext: {}
      containers:
      - name: "cassandra"
        securityContext: {}
      securityContext: {}

