apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: saberkan-rabbit-standalone
  namespace: ndc-catalog-demo
spec:
  image: docker.io/saberkan/rabbitmq:3.8.21-management
  replicas: 2
  service:
    type: ClusterIP
  persistence:
    storageClassName: ocs-external-storagecluster-ceph-rbd
    storage: "1Gi"
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []
            securityContext: {}
            initContainers:
            - name: setup-container
              securityContext: {}

